os: linux

language: node_js
node_js:
- "node"

cache: npm


script:
- npm run lint
- npm run build

deploy:
  edge: true
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "AWS_SECRET_KEY"
  bucket: "castellers.clemissa.info-static"
  skip_cleanup: true
  local_dir: dist
  region: ca-central-1
  on:
    branch: travis-publish-s3