language: node_js

before_install:
- openssl aes-256-cbc -K $encrypted_b9416c471052_key -iv $encrypted_b9416c471052_iv
  -in travis-deploy.enc -out ./travis-deploy -d
- chmod 600 travis-deploy
- ssh-add travis-deploy

script:
- npm run lint
- npm run build
