language: node_js

before_install:
- openssl aes-256-cbc -K $encrypted_7eca150e901f_key -iv $encrypted_7eca150e901f_iv -in travis-deploy.enc -out travis-deploy -d
- eval "$(ssh-agent -s)"
- chmod 600 travis-deploy
- ssh-add travis-deploy

script:
- npm run lint
- npm run build